### ISSUE TITLE
Noto Sans Sundanese: Double vowel signs messed up 

### ISSUE THREAD

**Issue by Ilhamkang** [notofonts/sundanese#1]
I found some rendering problem for double signs messed up above a consonant and front-above consonant. Here's the sample on MS Word: 
![render-word](https://user-images.githubusercontent.com/22653757/29765528-b9a42c1e-8c05-11e7-92e5-edf32574e99e.png)
(above: Noto Sans Sundanese, below: "Sundanese Unicode" font by Unicode Aksara Sunda team in West Java). 

On Firefox the double sign above consonant looks overlapping to the next glyph: 
![noto-overlap](https://user-images.githubusercontent.com/22653757/29766509-2b76751a-8c09-11e7-9ecd-9a86b5a940c3.png)

Correct rendering should appears like "Sundanese Unicode" font above.

The phrase is read "deungkleung déngdék", with typing sequence: 
da+eu+anusvara+ka+subjoined la+eu+anusvara da+ae+anusvara+da+ae+ka+virama

I've reviewed the issue before: 
https://www.kairaga.com/2016/06/24/noto-sans-sundanese-font-aksara-sunda-besutan-google/

**Comment by r12a** [comment]
A particularly serious issue, which is not clearly mentioned above is the right-side positioning of the eu vowel-sign. It should be to the left. Should i raise a separate issue for that?

fwiw, you can test different fonts with the sequence at 
https://r12a.github.io/pickers/sundanese/?text=%E1%AE%93%E1%AE%A9%E1%AE%80%E1%AE%8A%E1%AE%A3%E1%AE%A9%E1%AE%80%20%E1%AE%93%E1%AE%A6%E1%AE%80%E1%AE%93%E1%AE%A6%E1%AE%8A%E1%AE%AA

Sundanese Unicode 2013 positions it correctly. Noto Sans Sundanese doesn't.

**Comment by Ilhamkang** [comment]
Yes, indeed. The **eu** vowel-sign should move to the left, so the double sign will be center-aligned above the consonant. Here are positioning samples of signs.

![positioning](https://user-images.githubusercontent.com/22653757/29824629-396df334-8cfc-11e7-9ec6-3e5a042f904f.jpg)

I've reproduced various sequences with double and triple signs combination here: 
https://r12a.github.io/pickers/sundanese/?text=%E1%AE%98%E1%AE%A3%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A4%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A5%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A8%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A9%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A7%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A6%E1%AE%80%20%20%20%0Ablang%20bling%20blung%20bleng%20bleung%20blong%20bl%C3%A9ng%20%0A%E1%AE%98%E1%AE%A1%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A4%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A5%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A8%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A9%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A7%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A6%E1%AE%80%20%0Abyang%20bying%20byung%20byeng%20byeung%20byong%20by%C3%A9ng%0A%E1%AE%98%E1%AE%A2%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A4%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A5%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A8%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A9%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A7%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A6%E1%AE%80%20%0Abrang%20bring%20brung%20breng%20breung%20brong%20br%C3%A9ng

Again, Sundanese Unicode 2013 renders them correctly, but Noto Sans Sundanese does not.

**Comment by marekjez86** [comment]
[NotoSansSundanese-Regular.otf.zip](https://github.com/googlei18n/noto-fonts/files/1516412/NotoSansSundanese-Regular.otf.zip)

@Ilhamkang , @r12a : could you verify that it was fixed in the font above? Thank you

**Comment by Ilhamkang** [comment]
There still several glitches on triple sign sequences, especially when dealing with "panolong/o vowel sign". Here they are:
![blong](https://user-images.githubusercontent.com/22653757/33413463-3ac51170-d5c4-11e7-8918-b09bf3d605cc.png)

the triple signs with "panaelaeng/ae vowel sign" are fine. 

They should appear like this: 
https://r12a.github.io/pickers/sundanese/?text=%E1%AE%98%E1%AE%A2%E1%AE%A7%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A7%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A7%E1%AE%80%0A%E1%AE%98%E1%AE%A2%E1%AE%A6%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A6%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A6%E1%AE%80

**Comment by marekjez86** [comment]
@Ilhamkang : thank you! we'll investigate it

**Comment by marekjez86** [comment]
The text:
 ᮘᮢᮧᮀ ᮘᮣᮧᮀ ᮘᮡᮧᮀ

Expected 

![sund-959-expected](https://user-images.githubusercontent.com/13322623/33586502-84784e7e-d91e-11e7-9d32-5e2f3c723094.jpeg)

Noto

![sund-959-noto](https://user-images.githubusercontent.com/13322623/33586508-8cddd0ca-d91e-11e7-8698-4ecca0a29146.jpeg)

**Comment by nizarsq** [comment]
The issue with the triple sign sequences still reproducible
<img width="1229" alt="Screen Shot 2020-08-08 at 9 53 56 PM" src="https://user-images.githubusercontent.com/22158882/89725177-aba73900-d9c1-11ea-9cb5-ae47813814cd.png">

**Comment by simoncozens** [comment]
I have fixed some of these; however, the text ᮒᮢᮡ seems to appear in some text, and I don't know how that should be handled. Do we need a new ligature?

**Comment by Ilhamkang** [comment]
Can you bring the text sample that uses this ᮒᮢᮡ  sequence? I believe the modern Sundanese language has no lemma with this cluster. 

There is a possible word in old Sundanese that close to this cluster: **triyak/tryak** but the manuscript showed using **triyak** cluster instead of **tryak**.  
![image](https://user-images.githubusercontent.com/22653757/188514634-6d20651d-7461-410c-848b-ae5cb730aa12.png)
_triyak_

**Comment by simoncozens** [comment]
This is from our text samples repository. (I'm not sure where it comes from, but it may be an automatically "transcribed" version of the UN Declaration of Human Rights)

"ᮃᮞᮡᮀ ᮃᮘᮤᮌᮧᮯᮔᮚᮀ ᮔᮤᮁᮓᮤᮯ᮪ᮒᮂ ᮞᮁᮝᮨᮺᮕᮤ ᮃᮓᮤᮊᮛᮂ ᮞᮁᮝᮔᮡᮕᮤ ᮎ ᮞ᮪ᮝᮒᮔ᮪ᮒᮢᮡᮔᮤ, ᮝᮤᮔᮄᮝ ᮏᮒᮤᮝᮁᮔᮜᮤᮀᮌᮘᮯᮓᮁᮙᮛᮏᮔᮤᮒᮤᮊᮒᮓᮤᮒᮛᮙᮔ᮪ᮒᮝᮡᮓᮤᮘᮨᮓᮙ᮪, ᮛᮯ᮪ᮒᮢᮤᮚᮀ ᮞᮙᮏᮤᮊᮓᮛᮀ ᮞᮙ᮪ᮕᮏ᮪ᮏᮔ᮪ᮙᮒᮓᮤᮒᮛ ᮞ᮪ᮒᮛᮑ᮪ᮎ ᮃᮝᮤᮌᮔᮚᮡ, ᮃᮓᮤᮌᮔ᮪ᮒᮥᮀ ᮞᮁᮝᮧᮺᮕᮤ ᮏᮔᮂ ᮕᮢᮘᮝᮒᮤ."

**Comment by Ilhamkang** [comment]
Well, the sample is most probably the Sanskrit language, not Sundanese. This is why the sequence ᮒᮢᮡ occurred, which will not naturally occur in modern Sundanese and old Sundanese. The modern Sundanese has the rule to handle the  ᮒᮢᮡ sequence using this: ᮒ᮪ᮛᮡ, while old Sundanese will handle it as ᮒᮢᮤᮚ _triya_.

In old Sundanese, several Sanskrit words were written rather differently than the original sound. For example, the word _bhaṭāra_ (Devanagari: भटर) can be written as _batara_ and _baṭara_. So it does not need perfectly match to the Sanskrit orthography. 
![image](https://user-images.githubusercontent.com/22653757/189238268-9e110a93-6948-4a1a-ae53-6bf54a850c45.png)

The Sundanese avagraha ᮺ function is not perfectly the same as other scripts that have it. I have evaluated this matter to revise the Unicode through a document: https://www.unicode.org/L2/L2021/21221-three-sundanese-chars.pdf

**Comment by simoncozens** [comment]
Since ᮒᮢᮡ is not attested I won't worry about that, but there are still some issues with the positioning of the anusvara.
