### ISSUE TITLE
U+1BA1 SUNDANESE CONSONANT SIGN PAMINGKAL overlaps the base letter

### ISSUE THREAD

**Issue by dscorbett** [notofonts/sundanese#6]
### Font
NotoSansSundanese-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/sundanese/releases/tag/NotoSansSundanese-v2.003
Date: 2022-10-10

### Font version
Version 2.003

### Issue
In version 2.003, U+1BA1 SUNDANESE CONSONANT SIGN PAMINGKAL is too close to, and sometimes overlaps, the base letter.

### Character data
ᮔᮡ
U+1B94 SUNDANESE LETTER NA
U+1BA1 SUNDANESE CONSONANT SIGN PAMINGKAL

### Screenshots
![ᮔᮡ](https://user-images.githubusercontent.com/1124347/194896180-8dbff328-adb7-4ceb-8dfa-96754e09d3cd.png)
Compare version 2.002:
![ᮔᮡ](https://user-images.githubusercontent.com/1124347/194896761-dfe443b9-e95a-4954-83bf-f52541178d7d.png)

**Comment by simoncozens** [comment]
This seems to be fixed as of 3aeca47:

![shape](https://github.com/notofonts/sundanese/assets/106728/d1658f02-46fe-4f6a-9e2f-1a5f6cc31f4d)
